# Generated by Django 4.2.4 on 2023-11-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ml', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='volume_option',
            field=models.ManyToManyField(blank=True, null=True, related_name='Объем', to='api.volume'),
        ),
    ]
