# Generated by Django 4.2.4 on 2023-11-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_volume_product_volume_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
