# Generated by Django 4.2.4 on 2023-11-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_brand_name_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='brand',
            index_together={('name', 'slug')},
        ),
    ]
